spring:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 250
        max-idle: 64
        max-wait: 3000ms
        min-idle: 2

redisson:
  address: redis://localhost:6379
