spring:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 1000ms
        min-idle: 2

