spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: false
      hibernate.enable_lazy_load_no_trans: true
    open-in-view: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 5
      initial-size: 5
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: false
      max-active: 20
      max-wait: 60000
      validation-query-timeout: 60
      keep-alive: true
      use-global-data-source-stat: true
      filters: stat,wall
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: true
            drop-table-allow: true
            create-table-allow: true
            alter-table-allow: true
            truncate-allow: true

  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  #config-location:  classpath:mybatis-config.xml
  check-config-location: false
  executor-type: reuse #ExecutorType.SIMPLE：该执行器类型不做特殊的事情，为每个语句的执行创建一个新的预处理语句（PreparedStatement）
  configuration:
    aggressive-lazy-loading: true
    lazy-loading-enabled: true
    auto-mapping-behavior: partial  #AutoMappingBehavior.NONE：不启用自动映射
    auto-mapping-unknown-column-behavior: none  #AutoMappingUnknownColumnBehavior.NONE：不做任何处理 (默认值)
    cache-enabled: true
    call-setters-on-nulls: false #指定当结果集中值为 null 的时候是否调用映射对象的 Setter（Map 对象时为 put）方法
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 #逻辑已删除值,(逻辑删除下有效)
      logic-not-delete-value: 0 #逻辑未删除值,(逻辑删除下有效)
      table-underline: true #表名、是否使用下划线命名，默认数据库表使用下划线命名

server:
  port: 8080